name: Build up document

on:
  push:
    branches: [ master ]

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: test
      run: echo "hello?"
